package Interfaces;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import java.net.URL;
import java.util.ResourceBundle;

import DaoProject.DaoUser;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.layout.AnchorPane;

import javafx.scene.layout.Pane;

public class SignupController implements Initializable {

	@FXML
	private Pane pansign;
	@FXML
	private Label Lbetesinscrit;
	@FXML
	private Pane Panesignup;
	@FXML
	private Label LbpasInscrit;
	@FXML
	private Button Btinscrire;
	@FXML
	private Button Btconnect;

	// Event Listener on Button[#Btinscrire].onAction
	@FXML
	public void Btinscrire(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#Btconnect].onAction
	@FXML
	public void Btconnect(ActionEvent event) {
		// TODO Autogenerated
	}
		  @FXML
		    void initialize() {
		  }
		
		@Override
		public void initialize(URL arg0, ResourceBundle arg1) {
			// TODO Auto-generated method stub
			
		}}
		    	
		    